apiVersion: apps/v1
kind: Deployment
metadata:
  # Changed name to 'iris-deployment-dev'
  name: iris-deployment-dev
spec:
  replicas: 1 # Only 1 replica for dev
  selector:
    matchLabels:
      app: iris-api-dev
  template:
    metadata:
      labels:
        app: iris-api-dev
    spec:
      containers:
      - name: iris-api-container
        image: __IMAGE_URL__ # This will be replaced by the pipeline
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: iris-service-dev
spec:
  type: LoadBalancer
  selector:
    app: iris-api-dev 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
