name: Build, Push, and Deploy to GKE

on:
  push:
    branches:
      - main
      - dev

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  AR_LOCATION: ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}
  AR_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
  IMAGE_NAME: iris-api

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.AR_LOCATION }}-docker.pkg.dev

    - name: Build and Tag the Docker Image
      id: build
      run: |
        # Because of unique tag it prevents 'dev' images from overwriting 'main' images
        export BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9]/-/g')
        export IMAGE_TAG="${{ env.AR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${BRANCH_NAME}-${{ github.sha }}"
        
        docker build -t $IMAGE_TAG .
        echo "IMAGE_URL=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Push the Docker Image
      run: docker push ${{ steps.build.outputs.IMAGE_URL }}

    - name: Get GKE cluster credentials
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Deploy to GKE
      run: |
        echo "Deploying image: ${{ steps.build.outputs.IMAGE_URL }}"
        
        # Replace the placeholder in deployment.yaml
        sed -i 's|__IMAGE_URL__|${{ steps.build.outputs.IMAGE_URL }}|g' deployment.yaml
        
        echo "--- Applying deployment.yaml ---"
        cat deployment.yaml
        echo "--------------------------------"
        
        # Apply the updated config to GKE
        kubectl apply -f deployment.yaml
